version: '2'

services:
  supplier1-ca:
    container_name: supplier1-ca
    extends:
      file: ./ca-base.yaml
      service: ca-base
    image: supplier1-ca
    ports:
    - 7054:7054

  supplier2-ca:
    container_name: supplier2-ca
    extends:
      file: ./ca-base.yaml
      service: ca-base
    image: supplier2-ca
    ports:
    - 8054:7054

  supplier3-ca:
    container_name: supplier3-ca
    extends:
      file: ./ca-base.yaml
      service: ca-base
    image: supplier3-ca
    ports:
    - 9054:7054

  orderer0:
    container_name: orderer0
    image: orderer
    environment:
    - ORDERER_GENERAL_LOGLEVEL=debug
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/orderer/crypto/genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/orderer/crypto/msp
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/orderer/crypto/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/orderer/crypto/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/orderer/crypto/tls/ca.crt]
    working_dir: /orderer
    command: orderer
    ports:
    - 7050:7050

  supplier1:
    container_name: supplier1
    extends:
      file: ./peer-base.yaml
      service: peer-base
    image: supplier1
    environment:
    - CORE_PEER_ID=supplier1
    - CORE_PEER_ADDRESS=supplier1:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=supplier1:7051
    - CORE_PEER_LOCALMSPID=InsuranceOrgMSP
    ports:
    - 7051:7051
    - 7053:7053
    depends_on:
    - orderer0

  supplier2:
    container_name: supplier2
    extends:
      file: ./peer-base.yaml
      service: peer-base
    image: supplier2
    environment:
    - CORE_PEER_ID=supplier2
    - CORE_PEER_ADDRESS=supplier2:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=supplier2:7051
    - CORE_PEER_LOCALMSPID=ShopOrgMSP
    ports:
    - 8051:7051
    - 8053:7053
    depends_on:
    - orderer0
    - supplier1

  supplier3:
    container_name: supplier3
    extends:
      file: ./peer-base.yaml
      service: peer-base
    image: supplier3
    environment:
    - CORE_PEER_ID=supplier3
    - CORE_PEER_ADDRESS=supplier3:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=supplier3:7051
    - CORE_PEER_LOCALMSPID=RepairShopOrgMSP
    ports:
    - 9051:7051
    - 9053:7053
    depends_on:
    - orderer0
    - supplier1
    - supplier2
